defmodule Nonprofiteer.Repo.Migrations.EfileFilingPersonUpserts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:people) do
      add :part_vii_sequence, :bigint
    end

    create unique_index(:people, [:filing_id, :part_vii_sequence],
             name: "people_unique_filing_person_index"
           )

    alter table(:filings) do
      add :filed_on, :date
      add :schema_version, :text
    end

    create unique_index(:filings, [:source_object_id],
             name: "filings_unique_source_object_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:filings, [:source_object_id],
                     name: "filings_unique_source_object_id_index"
                   )

    alter table(:filings) do
      remove :schema_version
      remove :filed_on
    end

    drop_if_exists unique_index(:people, [:filing_id, :part_vii_sequence],
                     name: "people_unique_filing_person_index"
                   )

    alter table(:people) do
      remove :part_vii_sequence
    end
  end
end
