defmodule Nonprofiteer.Repo.Migrations.BmfIngestOrgSourceAndIngestRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :source, :text
      add :gen, :text
    end

    create unique_index(:organizations, [:ein],
             name: "organizations_unique_bmf_ein_index",
             where: "(source = 'bmf')"
           )

    create table(:ingest_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :extract_id, :text
      add :status, :text, null: false
      add :row_count, :bigint, null: false, default: 0
      add :orphan_skipped_count, :bigint, null: false, default: 0
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:ingest_runs, [:inserted_at])

    create index(:ingest_runs, [:source, :extract_id])
  end

  def down do
    drop_if_exists index(:ingest_runs, [:source, :extract_id])

    drop_if_exists index(:ingest_runs, [:inserted_at])

    drop table(:ingest_runs)

    drop_if_exists unique_index(:organizations, [:ein],
                     name: "organizations_unique_bmf_ein_index"
                   )

    alter table(:organizations) do
      remove :gen
      remove :source
    end
  end
end
