defmodule Nonprofiteer.Repo.Migrations.AddFilingsAndPeople do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:people, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :title, :text
      add :tombstoned_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "people_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :filing_id, :uuid, null: false
      add :address_id, :uuid
      add :superseded_by_id, :uuid
    end

    create index(:people, [:filing_id])

    create index(:people, [:organization_id])

    create table(:filings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:people) do
      modify :filing_id,
             references(:filings,
               column: :id,
               name: "people_filing_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :address_id,
             references(:addresses,
               column: :id,
               name: "people_address_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :superseded_by_id,
             references(:people,
               column: :id,
               name: "people_superseded_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:filings) do
      add :return_type, :text
      add :tax_year, :bigint, null: false
      add :source_object_id, :text
      add :tombstoned_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "filings_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :superseded_by_id,
          references(:filings,
            column: :id,
            name: "filings_superseded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:filings, [:tax_year])

    create index(:filings, [:organization_id])
  end

  def down do
    drop constraint(:filings, "filings_organization_id_fkey")

    drop constraint(:filings, "filings_superseded_by_id_fkey")

    drop_if_exists index(:filings, [:organization_id])

    drop_if_exists index(:filings, [:tax_year])

    alter table(:filings) do
      remove :superseded_by_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :tombstoned_at
      remove :source_object_id
      remove :tax_year
      remove :return_type
    end

    drop constraint(:people, "people_filing_id_fkey")

    drop constraint(:people, "people_address_id_fkey")

    drop constraint(:people, "people_superseded_by_id_fkey")

    alter table(:people) do
      modify :superseded_by_id, :uuid
      modify :address_id, :uuid
      modify :filing_id, :uuid
    end

    drop table(:filings)

    drop constraint(:people, "people_organization_id_fkey")

    drop_if_exists index(:people, [:organization_id])

    drop_if_exists index(:people, [:filing_id])

    drop table(:people)
  end
end
