defmodule Nonprofiteer.Repo.Migrations.AddOrganizationsAndAddresses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ein, :text
      add :name, :text, null: false
      add :ntee_code, :text
      add :tombstoned_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :address_id, :uuid
      add :central_org_id, :uuid
      add :superseded_by_id, :uuid
    end

    create index(:organizations, [:ein])

    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:organizations) do
      modify :address_id,
             references(:addresses,
               column: :id,
               name: "organizations_address_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :central_org_id,
             references(:organizations,
               column: :id,
               name: "organizations_central_org_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :superseded_by_id,
             references(:organizations,
               column: :id,
               name: "organizations_superseded_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:addresses) do
      add :line1, :text
      add :line2, :text
      add :city, :text
      add :region, :text
      add :postal_code, :text
      add :country, :text, default: "US"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:addresses) do
      remove :updated_at
      remove :inserted_at
      remove :country
      remove :postal_code
      remove :region
      remove :city
      remove :line2
      remove :line1
    end

    drop constraint(:organizations, "organizations_address_id_fkey")

    drop constraint(:organizations, "organizations_central_org_id_fkey")

    drop constraint(:organizations, "organizations_superseded_by_id_fkey")

    alter table(:organizations) do
      modify :superseded_by_id, :uuid
      modify :central_org_id, :uuid
      modify :address_id, :uuid
    end

    drop table(:addresses)

    drop_if_exists index(:organizations, [:ein])

    drop table(:organizations)
  end
end
